name: Kivy APK Build

on:
  push:
    branches: [ main ]

jobs:
  build-apk:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip openjdk-17-jdk unzip
          pip install buildozer cython

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: kivy-apk
          path: bin/*.apk
